### ISSUE TITLE
The eventmanager has an issue

### ISSUE THREAD

**Issue by JordivdMolen** [jorisguffens/KingdomCraft#5]
I need to be able to de-register an event.
When we reload a plugin that updates a database it does it +1 times for every reload.

**Comment by jorisguffens** [comment]
Sorry for the late reaction. When adding an event listener with EventManager#addListener it returns an instance of EventExecutor, you can call unregister() on an EventExecutor.

**Comment by JordivdMolen** [comment]
Ooh my mistake then thanks a lot!
